config/routes.rb
Controlsafe::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get :terms_and_conditions, to: 'welcome#terms_and_conditions'
  get :swap_forms, to: 'welcome#swap_forms'
  get :send_email, to: 'welcome#send_email'
  
  get :order_due_diligence, to: 'orders#order_due_diligence'
  get :search_document_safes, to: 'orders#search_document_safes'
  get :add_to_cart, to: 'orders#add_to_cart'
  get :document_safe_orders, to: 'orders#document_safe_orders'
  get :review_due_diligence, to: 'orders#review_due_diligence'

  resources :document_safes do
    resources :documents
  end

  resources :documents

  resources :brokers do
    resources :orders
  end

  resources :lawyers do
    resources :orders
  end

  resources :orders do
    get :autocomplete_document_safe_street_address, on: :collection
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.manager?
      can [:index, :new, :create], DocumentSafe
      can [:update, :destroy, :show], DocumentSafe do |document_safe|
        document_safe.try(:manager) == user
      end

      can :create, Document
      can [:show, :index, :update, :destroy, :edit], Document do |document|
        document.document_safe.try(:manager) == user
      end
      can [:index, :document_safe_orders, :show], Order
    elsif user.lawyer?
      can :show, Document
      can [:order_due_diligence,
           :autocomplete_document_safe_street_address,
           :search_document_safes,
           :add_to_cart,
           :new,
           :preload_checkout_documents,
           :create,
           :index,
           :review_due_diligence], Order
      can :show, Order do |order|
        order.try(:customer_user) == user
      end
    elsif user.broker?
      can [:order_due_diligence,
           :autocomplete_document_safe_street_address,
           :search_document_safes,
           :add_to_cart,
           :new,
           :preload_checkout_documents,
           :create,
           :index], Order
      can :show, Order do |order|
        order.try(:customer_user) == user
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/board_minute.rb
class BoardMinute < Document
  validates :publish_date, presence: true
  validate :minimum_price

  def minimum_price
    errors.add(:price, "can't be less than $2.00") if self.price.to_f < 2.00
  end
end

app/models/broker.rb
class Broker < CustomerUser
end

app/models/customer_user.rb
class CustomerUser < User
  has_many :orders
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :order_items
  belongs_to :document_safe
  has_attached_file :doc,
                    s3_protocol: 'https',
                    s3_credentials: S3_CREDENTIALS,
                    s3_permissions: :private,
                    path: 'documents/:id/:filename'
  validates_attachment :doc, presence: true, 
                        content_type: { content_type: "application/pdf" }
  validates :type, presence: true
  validates :price, presence: true, format: { with: /\d+[.]\d{2}/ }
  validates :document_safe, presence: true

  def offering_plan?
    type == 'OfferingPlan'
  end

  def board_minute?
    type == 'BoardMinute'
  end

  def financial_statement?
    type == 'FinancialStatement'
  end
end

app/models/document_safe.rb
class DocumentSafe < ActiveRecord::Base
  has_many :documents
  has_many :financial_statements
  has_many :offering_plans
  has_many :board_minutes
  has_many :orders
  belongs_to :manager
  validates :building_name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :manager, presence: true
end

app/models/financial_statement.rb
class FinancialStatement < Document
  validates :publish_date, presence: true
  validate :minimum_price

  def minimum_price
    errors.add(:price, "can't be less than $75.00") if self.price.to_f < 75.00
  end
end

app/models/lawyer.rb
class Lawyer < CustomerUser
end

app/models/manager.rb
class Manager < User
  has_many :document_safes
  validates :position, presence: true
end

app/models/offering_plan.rb
class OfferingPlan < Document
  validate :minimum_price

  def minimum_price
    errors.add(:price, "can't be less than $150.00") if self.price.to_f < 150.00
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :customer_user
  belongs_to :document_safe
  validates :customer_user, presence: true
  validates :document_safe, presence: true
  validates :price, presence: true
  validates :sales_tax, presence: true
  validates :total_price, presence: true
  validates :recipient_name, presence: true
  validates :recipient_email, presence: true, 
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :apartment_number, presence: true
  validates :authorization_code, uniqueness: true

  def self.create_authorization_code
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    string = (0...50).map { o[rand(o.length)] }.join
    authorization_code = [SecureRandom.base64, SecureRandom.hex, string].sample.to_s
  end

  def create_order_number
    update_attribute(:order_number, "CSF-%.6d" % id)
  end

  def include_offering_plan?
    order_items.map(&:document).map(&:type).include? 'OfferingPlan'
  end

  def include_financial_statements?
    order_items.map(&:document).map(&:type).include? 'FinancialStatement'
  end

  def include_board_minutes?
    order_items.map(&:document).map(&:type).include? 'BoardMinute'
  end

  def offering_plan
    order_items.map(&:document).map do |document|
      document if document.offering_plan?
    end.reject do |document| 
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def financial_statements
    order_items.map(&:document).map do |document|
      document if document.financial_statement?
    end.reject do |document|
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def board_minutes
    order_items.map(&:document).map do |document|
      document if document.board_minute?
    end.reject do |document|
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def expired?
    (Date.today - created_at.to_date).to_i > 30
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  has_many :order_item_views
  belongs_to :order
  belongs_to :document
  validates :order, presence: true
  validates :document, presence: true
end

app/models/order_item_view.rb
class OrderItemView < ActiveRecord::Base
  belongs_to :order_item
  validates :order_item, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true 
  validates :type, presence: true 
  validates :first_name, presence: true 
  validates :last_name, presence: true 
  validates :phone_number, presence: true 
  validates :company_name, presence: true 
  validates :company_street_address, presence: true 
  validates :company_state, presence: true 
  validates :company_zip, presence: true 
  validates :company_city, presence: true 

  def fullname
    "#{first_name} #{last_name}"
  end

  def manager?
    type == 'Manager'
  end

  def lawyer?
    type == 'Lawyer'
  end

  def broker?
    type == 'Broker'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user 
  end 
  
  def resource
    @resource ||= User.new 
  end 
  
  def devise_mapping 
    @devise_mapping ||= Devise.mappings[:user] 
  end 
  
  def resource_class
    User
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.haml
- unless flash.blank?
  - flash.each do |flash_type, flash_message|
    .joobstrab_area
      .container
        .row
          .col-sm-12
            %div{ class: "alert alert-#{flash_type == :notice ? "success" : "danger"} text-center" }
              %button{ type: 'button', class: :close, data: { dismiss: :alert} }x
              = flash_message

app/views/layouts/_footer.html.haml
- if user_signed_in?
  %footer.footer.navbar.navbar-default.navbar-fixed-bottom
    .container
      .row
        .col-lg-4
          ControlSafe © 2013
- else
  %footer.footer
    .container
      .row
        .col-lg-4
          ControlSafe © 2013

app/views/layouts/_header.html.haml
- if user_signed_in?
  = render 'layouts/logged_in_header'
- else
  = render 'layouts/logged_out_header'

app/views/layouts/_logged_in_header.html.haml
- if current_user.lawyer?
  = render template: 'layouts/user_headers/lawyer_header'
- elsif current_user.broker?
  = render template: 'layouts/user_headers/broker_header'
- elsif current_user.manager?
  = render template: 'layouts/user_headers/manager_header'

app/views/layouts/_logged_out_header.html.haml
%header#jump.header
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          %i.fa.fa-lock
      .collapse.navbar-collapse.hidden-xs
        %ul.nav.navbar-nav.navbar-right
          %li.active
            %a{href: "#jump0"} Home
          %li
            %a{href: "#jump1"} About
          %li
            %a{href: "#jump2"} Privacy
          %li
            %a{href: "#jump4"} Support
          %li
            %a{href: "#jump6"} Contact
      / /.navbar-collapse
      .collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li.active
            %a{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", href: "#jump0"} Home
          %li
            %a{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", href: "#jump1"} About
          %li
            %a{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", href: "#jump2"} Privacy
          %li
            %a{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", href: "#jump4"} Support
          %li
            %a{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", href: "#jump6"} Contact

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ControlSafe
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - if user_signed_in?
      .section
        .container
          = render 'layouts/flash'
          = yield
    - else
      = yield
    = render 'layouts/footer'

app/views/layouts/user_headers/broker_header.html.haml
%header#jump.header
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          %i.fa.fa-lock
      .collapse.navbar-collapse.hidden-xs
        %ul.nav.navbar-nav.navbar-right
          %li{ class: "#{'active' if params[:controller] == 'welcome'}" }
            = link_to 'Home', root_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders' && (params[:action] == 'order_due_diligence' || params[:action] == 'new')}" }
            = link_to 'Order Due Diligence', order_due_diligence_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders' && params[:action] == 'index'}" }
            = link_to 'My Orders', orders_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'registrations'}" }
            = link_to 'Profile', edit_user_registration_path, method: :get
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
      .collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li.active
            = link_to 'Home', root_path, method: :get
          %li
            = link_to 'Order Due Diligence', '', method: :get
          %li
            = link_to 'My Orders', '', method: :get
          %li
            = link_to 'Profile', edit_user_registration_path
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/user_headers/lawyer_header.html.haml
%header#jump.header
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          %i.fa.fa-lock
      .collapse.navbar-collapse.hidden-xs
        %ul.nav.navbar-nav.navbar-right
          %li{ class: "#{'active' if params[:controller] == 'welcome'}" }
            = link_to 'Home', root_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders' && params[:action] == 'review_due_diligence'}" }
            = link_to 'Review Due Diligence', review_due_diligence_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders' && (params[:action] == 'order_due_diligence' || params[:action] == 'new')}" }
            = link_to 'Order Due Diligence', order_due_diligence_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders' && params[:action] == 'index'}" }
            = link_to 'My Orders', orders_path, method: :get
          %li
            = link_to 'Profile', edit_user_registration_path, method: :get
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
      .collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li.active
            = link_to 'Home', root_path, method: :get
          %li
            = link_to 'Review Due Diligence', '', method: :get
          %li
            = link_to 'Order Due Diligence', '', method: :get
          %li
            = link_to 'My Orders', '', method: :get
          %li
            = link_to 'Profile', edit_user_registration_path
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/user_headers/manager_header.html.haml
%header#jump.header
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          %i.fa.fa-lock
      .collapse.navbar-collapse.hidden-xs
        %ul.nav.navbar-nav.navbar-right
          %li{ class: "#{'active' if params[:controller] == 'welcome'}" }
            = link_to 'Home', root_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'document_safes' && params[:action] == 'new'}" }
            = link_to 'Create Document Safe', new_document_safe_path, method: :get
          %li{ class: "#{'active' if (params[:controller] == 'document_safes' && params[:action] == 'index') || (params[:controller] == 'documents')}" }
            = link_to 'Open Document Safe', document_safes_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders'}" }
            = link_to 'Order History', orders_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'registrations'}" }
            = link_to 'Profile', edit_user_registration_path, method: :get
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
      .collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li{ class: "#{'active' if params[:controller] == 'welcome'}" }
            = link_to 'Home', root_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'document_safes'}" }
            = link_to 'Create Document Safe', new_document_safe_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'document_safes'}" }
            = link_to 'Open Document Safe', document_safes_path, method: :get
          %li{ class: "#{'active' if params[:controller] == 'orders'}" }
            = link_to 'Order History', '', method: :get
          %li{ class: "#{'active' if params[:controller] == 'registrations'}" }
            = link_to 'Profile', edit_user_registration_path
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete