config/routes.rb
Controlsafe::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get :terms_and_conditions, to: 'welcome#terms_and_conditions'
  get :swap_forms, to: 'welcome#swap_forms'
  get :send_email, to: 'welcome#send_email'
  
  get :order_due_diligence, to: 'orders#order_due_diligence'
  get :search_document_safes, to: 'orders#search_document_safes'
  get :add_to_cart, to: 'orders#add_to_cart'
  get :document_safe_orders, to: 'orders#document_safe_orders'
  get :review_due_diligence, to: 'orders#review_due_diligence'

  resources :document_safes do
    resources :documents
  end

  resources :documents

  resources :brokers do
    resources :orders
  end

  resources :lawyers do
    resources :orders
  end

  resources :orders do
    get :autocomplete_document_safe_street_address, on: :collection
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :order_items
  belongs_to :document_safe
  has_attached_file :doc,
                    s3_protocol: 'https',
                    s3_credentials: S3_CREDENTIALS,
                    s3_permissions: :private,
                    path: 'documents/:id/:filename'
  validates_attachment :doc, presence: true, 
                        content_type: { content_type: "application/pdf" }
  validates :type, presence: true
  validates :price, presence: true, format: { with: /\d+[.]\d{2}/ }
  validates :document_safe, presence: true

  def offering_plan?
    type == 'OfferingPlan'
  end

  def board_minute?
    type == 'BoardMinute'
  end

  def financial_statement?
    type == 'FinancialStatement'
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :clean_document_price, only: [:create, :update]

  def index
    session[:last_document_safe_page] = request.env['HTTP_REFERER']
    @document_safe = DocumentSafe.find(params[:document_safe_id])
    @documents = @document_safe.documents.order(publish_date: :desc).paginate(
      page: params[:page], per_page: 30)
  end

  def create
    @document_safe = DocumentSafe.find(params[:document_safe_id])
    @document = @document_safe.documents.new(document_params)
    @document.publish_date = nil if @document.type == 'OfferingPlan'
    if @document.save
      redirect_to document_safe_documents_path(@document_safe), 
        notice: 'Document was successfully added'
    else
      redirect_to document_safe_documents_path(@document_safe), 
        alert: 'Document was not successfully added'
    end
  end

  def edit
  end

  def update
    @document_safe = @document.document_safe
    if @document.update_attributes(document_params)
      redirect_to documents_path(document_safe_id: @document_safe.id), 
        notice: 'Document successfully updated'
    else
      redirect_to documents_path(document_safe_id: @document_safe.id), 
        alert: 'Document update failed'
    end
  end

  def destroy
    @document_safe = @document.document_safe
    @document.destroy
    redirect_to document_safe_documents_path(@document_safe), 
      notice: 'Document was successfully destroyed'
  end

  def show
    respond_to do |format|
      format.json do
        render json: { 
          html: render_to_string(
            template: 'documents/show.html.haml', layout: false) }
      end
      format.html { order_item_check }
    end
  end

  private

  def document_params
    params.require(:document).permit(:type, :price, :publish_date, :doc)
  end

  def order_item_check
    if params[:order_id].blank?
      redirect_to root_path, alert: 'Access Denied'
    else
      @order = Order.find(params[:order_id])
      if order_has_document?
        @order_item = @order.order_items.find_by(document_id: @document.id)
        @order_item.order_item_views.create
        if @document.board_minute?
          if @order_item.order_item_views.count > 1
            redirect_to root_path, alert: 'Board Minute has expired'
          end
        else
          redirect_to root_path, alert: 'Document has expired' if @order.expired?
        end
      else
        unless @order.order_items.map(&:document_id).include?(@document.id)
          redirect_to root_path, alert: 'Access Denied'
        end
      end
    end
  end

  def clean_document_price
    params[:document][:price].gsub!('$', '')
  end

  def order_has_document?
    @order.order_items.map(&:document_id).include?(@document.id)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/show_pages/_lawyer_board_minute_show.html.haml
.row
  .col-sm-12.text-center
    .board-minute-reader
      %h3 Board Minute Reader
      %p= "Session Reader: #{current_user.fullname}"
      %p= "Today's Date: #{Date.today}"
      %p= "Authorization Code: #{@order.authorization_code}"
      %p= "Minute Date: #{@document.publish_date}"
      %p.warning.text-center
        WARNING!
      %p.warning-description.text-center= "THE RULES OF #{@document.document_safe.building_name} AND THE SITE TERMS & CONDITIONS STRICTLY PROHIBIT ELECTRONICALLY COPYING, RECORDING, OR CAPTURING THE CONTENTS OF THIS PAGE. YOUR AUTHORIZATION IS LIMITED TO READING THIS PAGE ONLY. THIS PAGE CONTAINS FEATURES FOR SECURITY TRACKING PURPOSES"
      %p.pull-left Go back to read more minutes
      %p.pull-right This page can only be read once
      .iframe-wrapper
        %iframe{src: @document.doc.expiring_url(600), width: '100%', height: '6000'}
        .iframe-blocker
:javascript
  $(document.body).attr('oncontextmenu', "return false");

app/views/documents/show_pages/_lawyer_offering_plan_financial_statement_show.html.haml
.row
  .col-sm-2
  .col-sm-8
    - if @document.type == 'OfferingPlan'
      %h1.text-center= 'Offering Plan'
      %h2.text-center= @document.document_safe.street_address
    - else
      %h1.text-center= 'Financial Statement'
      %h2.text-center= @document.document_safe.street_address
      %h2.text-center= "Publish date: #{@document.publish_date}"
.row
  .col-sm-2
  .col-sm-8
    %iframe{src: @document.doc.expiring_url(600), width: '100%', height: '800'}
  .col-sm-2

app/views/documents/show_pages/_manager_document_show.html.haml
.row
  .col-sm-12
    %iframe{src: @document.doc.expiring_url(600), width: '100%', height: '800'}
.row
  .col-sm-12
    %ul.list-unstyled.list-inline.pull-right
      %li= link_to 'Edit', edit_document_path(@document), class: 'btn btn-primary'
      %li= link_to 'Delete', document_path(@document), confirm: 'Are you sure you want to delete this document?', method: :delete, class: 'btn btn-primary'