config/routes.rb
Controlsafe::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get :terms_and_conditions, to: 'welcome#terms_and_conditions'
  get :swap_forms, to: 'welcome#swap_forms'
  get :send_email, to: 'welcome#send_email'
  
  get :order_due_diligence, to: 'orders#order_due_diligence'
  get :search_document_safes, to: 'orders#search_document_safes'
  get :add_to_cart, to: 'orders#add_to_cart'
  get :document_safe_orders, to: 'orders#document_safe_orders'
  get :review_due_diligence, to: 'orders#review_due_diligence'

  resources :document_safes do
    resources :documents
  end

  resources :documents

  resources :brokers do
    resources :orders
  end

  resources :lawyers do
    resources :orders
  end

  resources :orders do
    get :autocomplete_document_safe_street_address, on: :collection
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def terms_and_conditions
    @template_directory = ''
    if params[:user_type] == 'manager'
      @template_directory = 'welcome/terms_and_conditions/manager_terms'
    elsif params[:user_type] == 'broker'
      @template_directory = 'welcome/terms_and_conditions/broker_terms'
    elsif params[:user_type] == 'lawyer'
      @template_directory = 'welcome/terms_and_conditions/lawyer_terms'
    end
  end

  def swap_forms
    respond_to do |format|
      if params[:user_type] == 'manager'
        format.json do
          render json: { 
            html: render_to_string(
              template: 'welcome/_manager_registration_form.html.haml', 
              layout: false) }
        end
      else
        format.json do
          render json: { 
            html: render_to_string(
              template: 'welcome/_lawyer_broker_registration_form.html.haml', 
              layout: false) }
        end
      end
    end
  end

  def send_email
    UserMailer.contact_form_email(
      params[:name], params[:email], params[:subject], params[:content]).deliver
    redirect_to root_path, notice: 'Your inquiry was sent'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_about.html.haml
#jump1.jumper
.section.type-2
  .container
    .section-headlines
      %h4 About Us
      %h2 Problems we are solving
    .row
      .col-sm-12
        %p When it comes to the labor intensive and error-prone tasks cooperatives, condominiums and real estate associations perform for prospective purchasers in connection with their due diligence review, ControlSafe.com is the smart solution. 
        %br
        %p With ControlSafe, real estate due diligence becomes a streamlined and efficient process with best practices ensured each step of the way.
        %br/ 
        %p Gone are the days of outdated or piecemeal due diligence documents ending up in the hands of a prospective purchaser. Co-op boards, for example, can now rest assured that every purchaser has relied upon the most current version of their proprietary lease and house-rules.
        %br/ 
        %p ControlSafe.com stops unauthorized document access. Every due diligence request is logged, every board minute reader’s identity verified, credentials are never assumed, and the details of who read what and when are archived.
        %br/ 
        %p ControlSafe.com prevents an organization’s original documents from being altered or lost and prevents unauthorized document reproduction.
        %br/ 
        %p ControlSafe.com maintains a critical separation between management staff and the legal representative of a prospective purchaser. Gone are the burdens of office visits and the legal risks associated with the impromptu conversations such visits occasion. An unintentional, but nevertheless legally binding statement, for example, about a condo’s renovation policy is the sort of mistake ControlSafe prevents.
        %br/ 
        %p Gone too are the days of endless environmentally wasteful copies, the pestering phone calls, the unnecessary messengers, the needless postage, the wasted staff time, and the all around headaches associated with outmoded due diligence document production.
        %br/ 
        %p ControlSafe.com offers significant benefits to prospective purchasers and their representatives, too. When considering the costs of professional time, document printing, and performing due diligence without technology, a purchaser can expect to save money and their representatives can expect to save time.
        %br/ 
        %p ControlSafe.com has a simple to use credit card payment process. A prospective purchaser doesn’t have to waste more money messengering a check and no one has to waste time verifying and processing payment.
        %br/ 
        %p Every ControlSafe.com user, whether manager, lawyer, or broker, benefits from the best practices ControlSafe.com establishes for cooperatives, condominiums and real estate associations.

app/views/welcome/_contact.html.haml
#jump6.jumper
.section.type-1.section-contact
  .container
    .section-headlines
      %h4
        Contact Us
        %h2 We are here to help
    %form
      .row
        .col-lg-4
          %address
            .address-row
              .address-sign
                %i.fa.fa-map-marker
              %div{style: "address-info"}
                %b> ControlSafe LLC
                %br/
                80 Maiden Lane
                %br/
                New York, NY 10038
            %hr/
            .address-row
              .address-sign
                %i.fa.fa-envelope
              %div{style: "address-info"}
                %b Email:
                <a href="mailto:info@controlsafe.com">info@controlsafe.com</a>
            %hr/
            .address-row
              .address-sign
                %i.fa.fa-phone
              %div{style: "address-info"}
                %b Phone:
                (212) 430-6030
            %hr/
            .address-row
              .address-sign
                %i.fa.fa-time
              %div{style: "address-info"}
                %b 10am - 6pm (EST)
                %br/
                Monday through Friday
          .visible-xs.visible-sm
            %br.gap-30/
            %hr.gap-divider/
            %br.gap-30/
        .col-lg-7.col-lg-offset-1
          %form
          = form_tag send_email_path, method: :get do
            .form-group
              .row
                .col-lg-6
                  = text_field_tag :name, '', placeholder: 'Your Name *', class: 'form-control'
                  %br.gap-15/
                .col-lg-6
                  = text_field_tag :email, '', placeholder: 'Your Email *', required: true, class: 'form-control'
            .form-group
              = text_field_tag :subject, '', placeholder: 'Subject', class: 'form-control'
            .form-group
              = text_area_tag :content, '', rows: 8, required: true, class: 'form-control'
            = submit_tag 'Send Email', class: 'btn btn-block btn-primary'

app/views/welcome/_home.html.haml
#jump0.jumper
.section.type-1.big.splash
  .welcome-page-flash
    = render 'layouts/flash'
  .splash-cover
    .centered-home
      .container
        .section-headlines
          %h1 Welcome to ControlSafe
          %p Where Smart Cooperatives, Condominiums and Real Estate Organizations Harness Technology to Ensure Best Practices
        %a.btn.btn-outline.btn-lg{href: '', data: { toggle: 'modal', target: '#registerModal' } }
          Register
        %a.btn.btn-outline.btn-lg{href: '', data: { toggle: 'modal', target: '#signinModal' } }
          Sign in
= render 'signin_modal'
= render 'register_modal'

app/views/welcome/_lawyer_broker_registration_form.html.haml
.form-group
  = label_tag :user_first_name, 'First name'
  = text_field_tag :user_first_name, nil, autofocus: true, class: 'form-control', required: true, name: 'user[first_name]'
.form-group
  = label_tag :user_last_name, 'Last name'
  = text_field_tag :user_last_name, nil, class: 'form-control', required: true, name: 'user[last_name]'
.form-group
  = label_tag :user_email, 'Email'
  = text_field_tag :user_email, nil, class: 'form-control', required: true, name: 'user[email]', id: 'lawyer-broker-registration-email'
.form-group
  = label_tag :user_password, 'Password'
  = password_field_tag :user_password, nil, class: 'form-control', required: true, name: 'user[password]', id: 'lawyer-broker-registration-password'
.form-group
  = label_tag :user_password_confirmation, 'Password confirmation'
  = password_field_tag :user_password_confirmation, nil, class: 'form-control', required: true, name: 'user[password_confirmation]', id: 'lawyer-broker-registration-password-confirmation'
.form-group
  = label_tag :user_phone_number, 'Phone number'
  = text_field_tag :user_phone_number, nil, class: 'form-control', name: 'user[phone_number]'
.form-group
  = label_tag :user_company_name, 'Company name'
  = text_field_tag :user_company_name, nil, class: 'form-control', name: 'user[company_name]'
.form-group
  = label_tag :user_company_street_address, 'Street address'
  = text_field_tag :user_company_street_address, nil, class: 'form-control', name: 'user[company_street_address]'
.form-group
  = label_tag :user_company_city, 'City'
  = text_field_tag :user_company_city, nil, class: 'form-control', name: 'user[company_city]'
.form-group
  = label_tag :user_company_state, 'State'
  = select_tag :user_company_state, options_for_select(['AL','AK','AZ','AR','CA','CO','CT','DC','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'], {selected: 'NY'}), class: 'form-control', name: 'user[company_state]'
.form-group
  = label_tag :user_company_zip, 'Zip'
  = text_field_tag :user_company_zip, nil, class: 'form-control', name: 'user[company_zip]'
%h3 Billing Information
.form-group
  = label_tag 'credit_card[card_number]', 'Credit Card Number'
  = text_field_tag 'credit_card[card_number]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[expiration_year]', 'Expiration Year (must be 4 digits)'
  = text_field_tag 'credit_card[expiration_year]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[expiration_month]', 'Expiration Month (must be 2 digits)'
  = text_field_tag 'credit_card[expiration_month]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[security_code]', 'Security Code'
  = text_field_tag 'credit_card[security_code]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[name]', 'Full Name'
  = text_field_tag 'credit_card[name]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[phone_number]', 'Phone Number'
  = text_field_tag 'credit_card[phone_number]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[street_address]', 'Billing Street Address'
  = text_field_tag 'credit_card[street_address]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[city]', 'Billing City'
  = text_field_tag 'credit_card[city]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'credit_card[state]', 'Billing State'
  = select_tag 'credit_card[state]', options_for_select(['AL','AK','AZ','AR','CA','CO','CT','DC','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'], {selected: 'NY'}), class: 'form-control'
.form-group
  = label_tag 'credit_card[postal_code]', 'Billing Zip'
  = text_field_tag 'credit_card[postal_code]', nil, class: 'form-control', required: true

app/views/welcome/_manager_registration_form.html.haml
.form-group
  = label_tag :user_first_name, 'First name'
  = text_field_tag :user_first_name, nil, autofocus: true, class: 'form-control', required: true, name: 'user[first_name]'
.form-group
  = label_tag :user_last_name, 'Last name'
  = text_field_tag :user_last_name, nil, class: 'form-control', required: true, name: 'user[last_name]'
.form-group
  = label_tag :user_email, 'Email'
  = text_field_tag :user_email, nil, class: 'form-control', required: true, name: 'user[email]', id: 'manager-registration-email'
.form-group
  = label_tag :user_password, 'Password'
  = password_field_tag :user_password, nil, class: 'form-control', required: true, name: 'user[password]', id: 'manager-registration-password'
.form-group
  = label_tag :user_password_confirmation, 'Password confirmation'
  = password_field_tag :user_password_confirmation, nil, class: 'form-control', required: true, name: 'user[password_confirmation]', id: 'manager-registration-password-confirmation'
.form-group
  = label_tag :user_phone_number, 'Phone number'
  = text_field_tag :user_phone_number, nil, class: 'form-control', name: 'user[phone_number]'
.form-group
  = label_tag :user_company_name, 'Company name'
  = text_field_tag :user_company_name, nil, class: 'form-control', name: 'user[company_name]'
.form-group
  = label_tag :user_position, 'Position'
  = select_tag :user_position, options_for_select(['Principal', 'Employee'], {}), class: 'form-control', name: 'user[position]'
.form-group
  = label_tag :user_company_street_address, 'Street address'
  = text_field_tag :user_company_street_address, nil, class: 'form-control', name: 'user[company_street_address]'
.form-group
  = label_tag :user_company_city, 'City'
  = text_field_tag :user_company_city, nil, class: 'form-control', name: 'user[company_city]'
.form-group
  = label_tag :user_company_state, 'State'
  = select_tag :user_company_state, options_for_select(['AL','AK','AZ','AR','CA','CO','CT','DC','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'], {selected: 'NY'}), class: 'form-control', name: 'user[company_state]'
.form-group
  = label_tag :user_company_zip, 'Zip'
  = text_field_tag :user_company_zip, nil, class: 'form-control', name: 'user[company_zip]'
%h3 Account Receivable
.form-group
  = label_tag 'bank_account[name]', "Account Holder's Name"
  = text_field_tag 'bank_account[name]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'bank_account[routing_number]', 'Routing Number'
  = text_field_tag 'bank_account[routing_number]', nil, class: 'form-control', required: true
.form-group
  = label_tag 'bank_account[account_number]', 'Account Number'
  = text_field_tag 'bank_account[account_number]', nil, class: 'form-control', required: true

app/views/welcome/_privacy.html.haml
#jump2.jumper
.section.type-1{style: "padding-bottom: 0"}
  .container
    .section-headlines
      %h4 Privacy Policy
      %h2 We take privacy seriously
    .row
      .col-sm-12
        %br/ 
        %p ControlSafe.com is committed to handling our users' ("Users") private information in ways which preserve their on-line privacy, while at the same time ensuring a User’s use is in compliance with ControlSafe.com’s (“Site”) Terms & Conditions. 
        %br
        %p Aggregate information ("Aggregate Information") of Site Users, which generally is information that under ordinary circumstances could not be used to identify an individual, is used to improve our services and provide future services to all our Users.  We will not provide Aggregate Information to third parties not affiliated with this Site, except as otherwise set forth herein. 
        %br
        %p Non-personal information ("Non-personal Information"), such as a User's page visits and use patterns, is used by the Site to facilitate our Users' Site experience and to improve our services and to provide future services. We will not provide Non-personal Information to third parties not affiliated with this Site, except as otherwise set forth herein. 
        %br
        %p Personal information ("Personal Information") voluntarily provided to us is used in order to communicate with Users and/or to assist a User with conducting business on ControlSafe.com, except as to a User’s name and address and use log information, which is shared with the User(s) whose documentation and/or information the User requests and reviews. We will not otherwise provide a User’s Personal Information to third parties, except as otherwise further set forth herein.
        %br
        %p Personal activity ("Personal Activity "), such as queries, document requests, document reviews, emails, uploads and account information are monitored through the Site to ensure compliance with our Terms and Conditions. A User’s identifying information, which generally means their name, address and date and time of access, is shared with the User who owns and maintains the information the User has accessed through the Site. For this reason it is important to limit your business on the Site to matters concerning information or services provided and/or your transactions on the Site. We will not provide your Personal Activity to third parties who have no relationship to the information you access, except as otherwise set forth herein.
        %br
        %p Additional information ("Additional Information"), such as information which is the result of cookies, analytics, gif files, security watermark software, ControlSafe.com viewer security code or similar code used on the Site to ensure Site compliance is used by ControlSafe.com to ensure compliance with Site Terms & Conditions.  Users can at any time disable cookies in their browser if they do not wish us to use cookies; however, disabling cookies may cause some features to become unavailable or cause additional security features to activate. We will not provide your Additional Information to third parties, except as otherwise set forth herein.
        %br
        %p There are limited occasions when we will provide a User's Aggregate Information, Non-personal Information, Personal Information, Personal Activity and Additional Information to third parties, beyond your name and address and access date and time, to the User whose information a User has accessed: if we believe in good faith that doing so is necessary to protect the legal rights of other Users including ControlSafe.com; if we have reason to believe that a false statement has been made to us in a User’s registration or thereafter; if we believe that misleading information has been provided to us; if we believe that we must alert law enforcement of a potential crime, or in order to comply with a criminal investigation; or if a governmental entity requests information in order to comply with any regulation.
        %br
        %p This Privacy Policy does not apply to a User's name, address, email address, date and time of access when viewing or reviewing documents or information on this Site, which will be provided to the User who owns and maintains those documents on this Site to ensure compliance with Terms & Conditions compliance.
        %br
        %p It is important for all Site Users to use the most current and updated security software on their computers and electronic devices when using ControlSafe.com.  No electronic medium is one hundred percent (100%) secure; therefore, any information we collect from you or any information you share with us is at your own risk.
        %br
        %p From time to time we may modify this Privacy Policy.  When modifications are made all prior versions of our Privacy Policy shall be retained and the new Privacy Policy shall show the date of the modification on this page or a similar page.
        %br
        %p Questions about our Privacy Policy or requests to modify or exclude any information previously provided to us should be directed to <a href="mailto:info@controlsafe.com">info@controlsafe.com</a>
        %br
    %br/
    %br/
    %br/

app/views/welcome/_register_modal.html.haml
#registerModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Register
      .modal-body
        = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
          .form-group
            = f.label :type, 'Select'
            %br
            = f.radio_button :type, 'Broker', checked: true, class: "btn btn-default user-type"
            = f.label :type, 'Broker', class: "btn btn-default"
            = f.radio_button :type, 'Lawyer', class: "btn btn-default user-type"
            = f.label :type, 'Lawyer', class: "btn btn-default"
            = f.radio_button :type, 'Manager', class: "btn btn-default user-type"
            = f.label :type, 'Manager', class: "btn btn-default"
          .user-information-registration
            = render partial: 'lawyer_broker_registration_form', locals: { f: f }
          = link_to 'Terms and Conditions', terms_and_conditions_path(user_type: 'broker'), class: 'terms-and-conditions-link', target: '_blank'
          .form-group
            = check_box 'terms_and_conditions', nil, required: true
            = label_tag 'terms_and_conditions', 'I agree to the terms and conditions'
          %p.warning-message Warning! It is a crime (NYS Real Property Law Art. 12A Sec. 442-e) for an unlicensed person to act as a licensed real estate broker or licensed salesperson.
          = f.submit "Register", class: 'btn btn-primary'
.selected-user-type-info{ data: { user_type: 'broker' } }

app/views/welcome/_signin_modal.html.haml
#signinModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Sign in
      .modal-body
        = form_for(resource, :as => resource_name, :url => session_path(resource_name), html: { role: 'form' }) do |f|
          = flash[:alert]
          .form-group
            = f.label :email
            %br/
            = f.email_field :email, autofocus: true, class: 'form-control'
          .form-group
            = f.label :password
            %br/
            = f.password_field :password, class: 'form-control'
          - if devise_mapping.rememberable?
            .form-group
              = f.check_box :remember_me
              = f.label :remember_me
          = f.submit "Sign in", class: 'btn btn-primary'
        = render "devise/shared/links"

app/views/welcome/_support.html.haml
#jump4.jumper
.section.type-3
  .container
    .section-headlines
      %h4 Support
      %h2 Some Frequently Asked Questions
    .row
      .col-sm-12
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "Is there any monthly or recurring fee to use ControlSafe.com?", '#'
          %p.support-answers No.  Registered users incur no membership fees or recurring charges.
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "Why is a credit card required to register?", '#'
          %p.support-answers Registration for real   estate brokers and lawyers requires that you authenticate your identity with a credit card. However, your credit card will not be charged unless you purchase due diligence documents. 
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "Can I use my firm's credit card?", '#'
          %p.support-answers Yes.  An attorney or real   estate broker may register with the credit card belonging to their firm.
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "Can non-registered users, use ControlSafe.com to view due diligence documents?", '#'
          %p.support-answers No. To ensure compliance with site Terms & Conditions and the terms and conditions of our cooperatives, condominiums and real estate organizations, access to all site services is limited to registered users who meet the site requirements.
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "What format are documents in?", '#'
          %p.support-answers All site documents are  generally in pdf format.
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "What if my authorization code fails?", '#'
          %p.support-answers In most instances this  suggests that you have made a typographical error when entering your authorization code.  Log-out and re-enter your authorization code.  If this fails please contact us, and we will review the issue.
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "I never received my authorization code?", '#'
          %p.support-answers Please ensure that you are  looking in the email account the broker for the transaction has on file for you.  Please check your spam folder and otherwise contact us and we will investigate the issue.
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "Is use of ControlSafe.com limited to brokers, lawyers and managers?", '#'
          %p.support-answers Yes.  However, a paralegal working under the control and supervision of a site-registered user/attorney may use this site to review and obtain due diligence documents; an assistant to a site registered licensed real estate salesperson or real estate broker may use this site to place due diligence document orders; and the employee of a registered managing agent may use this site to maintain their account on behalf of that managing agent.
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "Can due diligence documents be searched?", '#'
          %p.support-answers Yes.  While reading due   diligence documents you may use a search or find feature to locate specific information.
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "When reviewing board minutes can I record the contents?", '#'
          %p.support-answers You may take your own notes; however, the taking of screen shots or electronically recording board minutes, in whole or part, is strictly prohibited and a substantial violation of site Terms & Conditions and the terms of the user owner (cooperative, condominium or real estate organization) which maintains the board minutes on the site.  Violations can be traced and will be reported to the cooperative, condominium or real estate organization, without exception, amongst the other remedies provided for in the site Terms & Conditions.  
        %br/
        .support-q-and-a
          %strong.support-questions=link_to "Can ControlSafe.com be used on handheld devices or tablets?", '#'
          %p.support-answers Controlsafe.com has been programmed to work on all platforms.  Its design is responsive, meaning the page contents will resize to fit your device. Try resizing this window, for example.  On very small devices the navigation bar will show as an accordion and can be selected to display it vertically.
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "Can ControlSafe.com be used from any computer and at any time?", '#'
          %p.support-answers Registered users can use ControlSafe.com 24/7 and from any computer or device to which the user has access.  In some rare instances a user's browser may not be supported. Please use Chrome, Internet Explorer, Firefox or Safari when viewing the site or contact us with the name and version of your browser for additional assistance.
        %br/  
        .support-q-and-a
          %strong.support-questions=link_to "I cannot scroll through the board minutes and/or I cannot find the next month’s minutes?", '#'
          %p.support-answers Make sure your cursor is pointed between the up and down arrows on the right of the minute reader window.  Mac users should drag the slide bar down after it appears.  Use the browser back arrow to go to the next set of unread minutes.
        %br
        .support-q-and-a
          %strong.support-questions=link_to "Can I read the board minutes on multiple occasions?", '#'
          %p.support-answers No. Your authorization is limited to one session.  Each set of board minutes can only be read once. 
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "What if the due diligence documents I am looking for are not on this site?", '#'
          %p.support-answers Let us know.  New building safes are being constructed on behalf of cooperatives, condominiums and real estate organizations on controlsafe.com every day.
        %br/ 
        .support-q-and-a
          %strong.support-questions=link_to "What if I have additional questions or need additional information?", '#'
          %p.support-answers Real people are here to help you. You may choose to email us, or to call.

app/views/welcome/index.html.haml
- if user_signed_in?
  - if current_user.manager?
    = render 'welcome/user_index_pages/manager_index'
  - elsif current_user.lawyer?
    = render 'welcome/user_index_pages/lawyer_index'
  - elsif current_user.broker?
    = render 'welcome/user_index_pages/broker_index'
- else
  = render 'home'
  = render 'about'
  = render 'privacy'
  = render 'support'
  = render 'contact'
  :javascript
    $('.nav-tabs a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
    })

app/views/welcome/terms_and_conditions.html.haml
.section
  .container
    .row
      .col-sm-12
        = render template: "#{@template_directory}", layouts: false