config/routes.rb
Controlsafe::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get :terms_and_conditions, to: 'welcome#terms_and_conditions'
  get :swap_forms, to: 'welcome#swap_forms'
  get :send_email, to: 'welcome#send_email'
  
  get :order_due_diligence, to: 'orders#order_due_diligence'
  get :search_document_safes, to: 'orders#search_document_safes'
  get :add_to_cart, to: 'orders#add_to_cart'
  get :document_safe_orders, to: 'orders#document_safe_orders'
  get :review_due_diligence, to: 'orders#review_due_diligence'

  resources :document_safes do
    resources :documents
  end

  resources :documents

  resources :brokers do
    resources :orders
  end

  resources :lawyers do
    resources :orders
  end

  resources :orders do
    get :autocomplete_document_safe_street_address, on: :collection
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :customer_user
  belongs_to :document_safe
  validates :customer_user, presence: true
  validates :document_safe, presence: true
  validates :price, presence: true
  validates :sales_tax, presence: true
  validates :total_price, presence: true
  validates :recipient_name, presence: true
  validates :recipient_email, presence: true, 
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :apartment_number, presence: true
  validates :authorization_code, uniqueness: true

  def self.create_authorization_code
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    string = (0...50).map { o[rand(o.length)] }.join
    authorization_code = [SecureRandom.base64, SecureRandom.hex, string].sample.to_s
  end

  def create_order_number
    update_attribute(:order_number, "CSF-%.6d" % id)
  end

  def include_offering_plan?
    order_items.map(&:document).map(&:type).include? 'OfferingPlan'
  end

  def include_financial_statements?
    order_items.map(&:document).map(&:type).include? 'FinancialStatement'
  end

  def include_board_minutes?
    order_items.map(&:document).map(&:type).include? 'BoardMinute'
  end

  def offering_plan
    order_items.map(&:document).map do |document|
      document if document.offering_plan?
    end.reject do |document| 
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def financial_statements
    order_items.map(&:document).map do |document|
      document if document.financial_statement?
    end.reject do |document|
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def board_minutes
    order_items.map(&:document).map do |document|
      document if document.board_minute?
    end.reject do |document|
      document.nil?
    end.sort { |a, b| b.publish_date <=> a.publish_date }
  end

  def expired?
    (Date.today - created_at.to_date).to_i > 30
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CartOperations
  before_action :authenticate_user!
  before_action :find_document_safe, only: [:new, :create, :order_due_diligence]
  autocomplete :document_safe, :street_address, class_name: 'DocumentSafe'
  load_and_authorize_resource

  def index
    if current_user.manager?
      @document_safes = current_user.document_safes.paginate(
        page: params[:page], per_page: 30)
    else
      @orders = current_user.orders.order(created_at: :desc).paginate(
        page: params[:page], per_page: 30)
    end
  end

  def document_safe_orders
    @orders = DocumentSafe.find(params[:document_safe_id]).orders.order(
      created_at: :desc).paginate(page: params[:page], per_page: 30)
    respond_to do |format|
      format.json do
        render json: { html: render_to_string(
          template: 'orders/document_safe_orders.html.haml', layout: false) }
      end
    end
  end

  def new
    preload_checkout_documents
    @apartment_number = params[:apartment_number]
    @cart_prices = CheckoutCalculator.new(params).cart_prices_info
  end

  def show
    respond_to do |format|
      format.json do
        render json: { html: render_to_string(
          template: 'orders/show.html.haml', layout: false) }
      end
    end
  end

  def create
    @order = current_user.orders.new(
      order_params.merge(document_safe: @document_safe, 
        authorization_code: Order.create_authorization_code))

    if @order.save
      @order.create_order_number
      OrderCheckoutOperations.new(order: @order,
                                  document_ids: create_document_ids,
                                  current_user: current_user).finalize_checkout
      redirect_to root_path, notice: 'Order successful!'
    else
      preload_checkout_documents
      @apartment_number = params[:apartment_number]
      @cart_prices = {price: order_params[:price],
                      sales_tax: order_params[:sales_tax],
                      total_price: order_params[:total_price]}
      render 'new'
    end
  end

  def review_due_diligence
    unless params[:authorization_code].blank?
      @order = Order.find_by(authorization_code: params[:authorization_code])

      if @order
        @offering_plan = @order.offering_plan
        @financial_statements = @order.financial_statements
        @board_minutes = @order.board_minutes
      else
        redirect_to review_due_diligence_path, 
          alert: 'Authorization code is invalid.'
      end
    end
  end
  
  def order_due_diligence
    if @document_safe
      @offering_plans = @document_safe.offering_plans
      @financial_statements = @document_safe.financial_statements.order(
        publish_date: :desc)
      @board_minutes = @document_safe.board_minutes.order(publish_date: :desc)
    end
  end

  def search_document_safes
    @document_safe = DocumentSafe.find_by(street_address: params[:building_address])
    if @document_safe
      redirect_to order_due_diligence_path(document_safe_id: @document_safe.id)
    else
      redirect_to order_due_diligence_path, 
        alert: "#{params[:building_address]} is not in our system."
    end
  end

  def add_to_cart
    if params[:method_caller] == 'order_missing_documents'
      cart_validator = CartValidator.new(
        MissingDocumentFinder.new(params[:order_id]).missing_document_hash)
    else
      cart_validator = CartValidator.new({offeringplan: params[:offeringplan],
                                          financialstatement: params[:financialstatement],
                                          boardminute: params[:boardminute],
                                          document_safe_id: params[:document_safe_id],
                                          method_caller: params[:method_caller]})
    end

    if !params[:order_id].blank? && missing_document_hash_is_empty?
      redirect_to review_due_diligence_path(
        authorization_code: Order.find(params[:order_id]).authorization_code), 
        alert: 'You already have all of the documents for this building'
    elsif cart_validator.valid?
      redirect_to new_order_path(cart_validator.optimize_cart.merge(
        document_safe_id: params[:document_safe_id],
        apartment_number: params[:apartment_number]))
    else
      redirect_to order_due_diligence_path(
        document_safe_id: params[:document_safe_id]), 
        alert: 'There was an error in your cart.'
    end
  end
  
  private

  def order_params
    params.require(:order).permit(:price,
                                  :sales_tax,
                                  :total_price,
                                  :recipient_name,
                                  :recipient_email,
                                  :apartment_number)
  end

  def create_document_ids
    document_ids = []
    document_ids += params[:offeringplan] if params[:offeringplan]
    document_ids += params[:financialstatement] if params[:financialstatement]
    document_ids += params[:boardminute] if params[:boardminute] 
    document_ids
  end

  def find_document_safe
    if params[:document_safe_id]
      @document_safe = DocumentSafe.find(params[:document_safe_id]) 
    end
  end

  def preload_checkout_documents
    unless params[:offeringplan].blank?
      @offering_plans = params[:offeringplan].map { |id| OfferingPlan.find(id) }
    end
    unless params[:freefinancialstatement].blank?
      @free_financial_statements = params[:freefinancialstatement].map { |id| FinancialStatement.find(id) }
      @free_financial_statements = params[:freefinancialstatement].map do |id|
        FinancialStatement.find(id)
      end
    end
    unless params[:financialstatement].blank?
      @financial_statements = params[:financialstatement].map do |id|
        FinancialStatement.find(id)
      end
    end
    unless params[:boardminute].blank?
      @board_minutes = params[:boardminute].map { |id| BoardMinute.find(id) }
    end
  end

  def missing_document_hash_is_empty?
    MissingDocumentFinder.new(
      params[:order_id]).missing_document_hash[:offeringplan].blank? && 
    MissingDocumentFinder.new(
      params[:order_id]).missing_document_hash[:financialstatement].blank? && 
    MissingDocumentFinder.new(
      params[:order_id]).missing_document_hash[:boardminute].blank?
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_apartment_form_section.html.haml
.row.text-center
  .col-sm-2
  .col-sm-8.apartment-information
    = label_tag :apartment_number, 'Documents requested in connection with the sale of apartment:'
    .row
      .col-sm-5
      .col-sm-2
        = text_field_tag :apartment_number, nil, placeholder: 'Unit #', class: 'form-control', required: true
      .col-sm-5
  .col-sm-2

app/views/orders/_checkout_errors.html.haml
- if @order
  - if @order.errors.any?
    #error_explanation
      .alert.alert-danger.text-center
        The form contains #{pluralize(@order.errors.count, "error")}.
        %ul.list-unstyled
          - @order.errors.full_messages.each do |msg|
            %li
              * #{msg}

app/views/orders/_checkout_hidden_fields.html.haml
- if @offering_plans
  - @offering_plans.map(&:id).each do |id|
    = hidden_field_tag 'offeringplan[]', id
- if @financial_statements && @free_financial_statements
  - (@free_financial_statements + @financial_statements).map(&:id).each do |id|
    = hidden_field_tag 'financialstatement[]', id
- elsif @financial_statements && @free_financial_statements.blank?
  - @financial_statements.map(&:id).each do |id|
    = hidden_field_tag 'financialstatement[]', id
- elsif @fiancial_statements.blank? && @free_financial_statements
  - @free_financial_statements.map(&:id).each do |id|
    = hidden_field_tag 'financialstatement[]', id
- if @board_minutes
  - @board_minutes.map(&:id).each do |id|
    = hidden_field_tag 'boardminute[]', id
= hidden_field_tag :document_safe_id, @document_safe.id
= f.hidden_field :apartment_number, value: @apartment_number
= f.hidden_field :price, value: @cart_prices[:price]
= f.hidden_field :sales_tax, value: @cart_prices[:sales_tax]
= f.hidden_field :total_price, value: @cart_prices[:total_price]

app/views/orders/_lawyer_broker_order_index.html.haml
.row
  .col-sm-3.document-safe-list
    %h2 Your Orders
    = render 'orders_list_table'
    = will_paginate @orders
  .col-sm-9.order-show

app/views/orders/_manager_order_index.html.haml
.row
  .col-sm-4.document-safe-list
    %h2 Your Document Safes Orders
    %h3 (Select Safe)
    %ul.list-group
      - @document_safes.each do |document_safe|
        %li.list-group-item.document-safe-orders-title= link_to document_safe.building_name, document_safe_orders_path(document_safe_id: document_safe.id), remote: true
    = will_paginate @document_safes
  .col-sm-8.document-safe-orders
.row
  .col-sm-12.document-safe-orders-information

app/views/orders/_orders_list_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Order Number
      %th Purchase Date
  %tbody
    - @orders.each do |order|
      %tr
        %td.order-number-link= link_to order.order_number, order_path(order), class: 'custom-active', remote: true
        %td= order.created_at.to_date

app/views/orders/_search_result_table.html.haml
- if params[:action] == 'new' || params[:action] == 'create'
  %table.table.table-hover
    %thead
      %tr
        - if documents.first.offering_plan?
          %th.text-center Title
        - else
          %th.text-center Publish date
        %th.text-center Price
    %tbody
      - documents.each do |document|
        %tr
          - if documents.first.offering_plan?
            %td Offering Plan
          - else
            %td= document.publish_date
          - if params[:freefinancialstatement].blank?
            %td= "$#{document.price}"
          - elsif params[:freefinancialstatement].include? document.id.to_s
            %td $0.00
          - else
            %td= "$#{document.price}"
- else
  %table.table.table-hover
    %thead
      %tr
        - unless documents.blank?
          - if documents.first.offering_plan?
            %th Title
          - else
            %th Publish date
          %th Price
          %th Add
      %tbody
        - documents.each do |document|
          %tr
            - if documents.first.offering_plan?
              %td Offering Plan
            - else
              %td= document.publish_date
            %td= "$#{document.price}"
            %td= check_box_tag "#{document.type.downcase}[]", document.id, false

app/views/orders/_search_results.html.haml
.row.document-safe-information
  .col-sm-12.text-center
    %h4 Documents provided by:
    %span= @document_safe.manager.company_name
    %br
    %span= @document_safe.street_address
    %br
    %span= "#{@document_safe.city} #{@document_safe.state} #{@document_safe.zip}"
.row.order-due-diligence-search-results
  = form_tag(add_to_cart_path(method_caller: 'order_due_diligence'), method: :get, html: { role: 'form' }) do
    = render 'apartment_form_section'
    %br
    .row
      .col-sm-4
        %a{id: 'check_all', class: 'btn btn-primary'}
          Check / Uncheck All Documents
      .col-sm-4
        %a{id: 'financial_statement_all', class: 'btn btn-primary'}
          Check / Uncheck All Financial Statements
      .col-sm-4
        %a{id: 'board_minute_all', class: 'btn btn-primary'}
          Check / Uncheck All Board Minutes
    .row.order-due-diligence-search-results
      .col-sm-4
        %h3.text-center Offering Plan and Last Two Years Financials
        %h4.text-center (Includes Financials)
        = render partial: 'search_result_table', object: @offering_plans, as: :documents
      .col-sm-4
        %h3.text-center Financial Statements
        %h4.text-center (Financials Only)
        = render partial: 'search_result_table', object: @financial_statements, as: :documents
      .col-sm-4
        %h3.text-center Board Minutes
        %h4.text-center (Minimum Order - 24 Months)
        = render partial: 'search_result_table', object: @board_minutes, as: :documents
      = hidden_field_tag :document_safe_id, nil, value: @document_safe.id
    = submit_tag 'Add Documents to Cart', disable_with: "Adding to cart...", class: 'btn btn-primary btn-lg pull-right'

:javascript
  $('#check_all').on("click", function(){ $('input[type="checkbox"]').click(); });
  $('#financial_statement_all').on("click", function(){ $('input[name="financialstatement[]"]').click(); });
  $('#board_minute_all').on("click", function(){ $('input[name="boardminute[]"]').click(); });

app/views/orders/document_safe_orders.html.haml
.row
  .col-sm-12
    = render 'orders_list_table'

app/views/orders/index.html.haml
- if current_user.manager?
  = render 'manager_order_index'
- else
  = render 'lawyer_broker_order_index'

app/views/orders/new.html.haml
.row
  .col-sm-12
    %h2.text-center Confirm your order
    .document-safe-information
      .col-sm-12.text-center
        %h4 Documents provided by:
        %span= @document_safe.manager.company_name
        %br
        %span= @document_safe.street_address
        %br
        %span= "#{@document_safe.city} #{@document_safe.state} #{@document_safe.zip}"
        %br
        %span= "Unit #: #{@apartment_number}"
.row.order-due-diligence-search-results.text-center
  = form_for([current_user, current_user.orders.build], method: :post, html: { role: 'form' }) do |f|
    = render 'checkout_errors'
    .col-sm-3
      .form-group
        = f.label :recipient_name
        %br
        %strong (Must be buyer's attorney)
        = f.text_field :recipient_name, class: 'form-control', required: true
      .form-group
        = f.label :recipient_email
        = f.text_field :recipient_email, class: 'form-control', required: true
    .col-sm-3
      %h4 Offering Plan 
      - if @offering_plans
        = render partial: 'search_result_table', object: @offering_plans, as: :documents
      - if @free_financial_statements
        %h4 Last Two Years Financials
        = render partial: 'search_result_table', object: @free_financial_statements, as: :documents
    .col-sm-3
      %h4 Financial Statements
      - if @financial_statements
        = render partial: 'search_result_table', object: @financial_statements, as: :documents
    .col-sm-3
      %h4 Board Minutes
      - if @board_minutes
        = render partial: 'search_result_table', object: @board_minutes, as: :documents
    = render partial: 'checkout_hidden_fields', locals: { f: f }
    .row
      .col-sm-9
      .col-sm-3
        %dl
          %dt Price
          %dd= "$#{@cart_prices[:price]}"
          %dt Sales Tax
          %dd= "$#{@cart_prices[:sales_tax]}"
          %dt Total Price
          %dd= "$#{@cart_prices[:total_price]}"
        = f.submit 'Checkout', disable_with: "Procesing...", class: 'btn btn-primary btn-lg'

app/views/orders/order_due_diligence.html.haml
.row
  .col-sm-4
    = form_tag(search_document_safes_path, method: :get, html: { role: 'form' } ) do
      .form-group
        = label_tag :building_address
        = autocomplete_field_tag :building_address, '', autocomplete_document_safe_street_address_orders_path, class: 'form-control', required: true
      = submit_tag 'Search', class: 'btn btn-primary'
.order-due-diligence-search-results
  - if @document_safe
    = render 'search_results'

app/views/orders/review_due_diligence.html.haml
.row  
  .col-sm-3
    = form_tag(review_due_diligence_path, method: :get, html: { role: 'form' }) do
      .form-group
        = label_tag :authorization_code, 'Authorization code (cut & paste)'
        = text_field_tag :authorization_code, nil, class: 'form-control'
      = submit_tag nil, class: 'btn btn-primary'
- if @order
  .row
    .col-sm-4
      %h2 Offering Plan
      %h3 (Select to View/Download/Print)
      - unless @offering_plan.empty?
        %ul.list-group
          - @offering_plan.each do |offering_plan|
            - if @order.expired?
              %li.list-group-item Offering Plan (expired)
            - else
              %li.list-group-item= link_to 'Offering Plan', document_path(offering_plan, order_id: @order.id)
    .col-sm-4
      %h2 Financial Statements
      %h3 (Select to View/Download/Print)
      - unless @financial_statements.empty?
        %ul.list-group
          -@financial_statements.each do |financial_statement|
            - if @order.expired?
              %li.list-group-item= "#{financial_statement.publish_date} (expired)"
            - else
              %li.list-group-item= link_to financial_statement.publish_date, document_path(financial_statement, order_id: @order.id)
    .col-sm-4
      %h2 Board Minutes
      %h3 (Select to read only once)
      - unless @board_minutes.empty?
        %ul.list-group
          - @board_minutes.each do |board_minute|
            - if @order.order_items.find_by(document: board_minute).order_item_views.count >= 1
              %li.list-group-item= "#{board_minute.publish_date} (expired)"
            - else
              %li.list-group-item= link_to board_minute.publish_date, document_path(board_minute, order_id: @order.id)
  .row
    .col-sm-12
      = link_to 'Order Missing Documents', add_to_cart_path(order_id: @order.id, method_caller: 'order_missing_documents', apartment_number: @order.apartment_number, document_safe_id: @order.document_safe.id), class: 'btn btn-primary pull-right'

app/views/orders/show.html.haml
.row
  .col-sm-7
    %dl.dl-order-information
      %dt Order #
      %dd= @order.order_number
      %dt Price
      %dd= "$#{@order.price}"
      %dt Sales Tax
      %dd= "$#{@order.sales_tax}"
      %dt Total Price
      %dd= "$#{@order.total_price}"
      %dt Purchaser Name
      %dd= User.find(@order.customer_user_id).fullname
      %dt Purchaser Email
      %dd= User.find(@order.customer_user_id).email
      %dt Recipient Name
      %dd= @order.recipient_name
      %dt Recipient Email
      %dd= @order.recipient_email
      %dt Authorization Code
      %dd= @order.authorization_code
      %dt Apartment Number
      %dd= @order.apartment_number
      %dt Order Number
      %dd= @order.order_number
      %dt Building Name
      %dd= @order.document_safe.building_name
  .col-sm-5
    %h2 Documents
    - if @order.include_offering_plan?
      %h4 Offering Plan
      %ul.list-group
        %li.list-group-item Offering Plan
    - if @order.include_financial_statements?
      %h4 Financial Statements
      - @order.financial_statements.each do |financial_statement|
        %ul.list-group
          %li.list-group-item= financial_statement.publish_date
    - if @order.include_board_minutes?
      %h4 Board Minutes
      - @order.board_minutes.each do |board_minute|
        %ul.list-group
          %li.list-group-item= board_minute.publish_date